spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xunblog?useUnicode=true&serverTimezone=UTC&setCharacterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: szx123
  thymeleaf:
    cache: false
    mode: HTML
  profiles:
    active: env1

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.szx.pojo






---
server:
  port: 8888
spring:
  profiles: env1
---
server:
  port: 9999
spring:
  profiles: env2
---
